---
"$schema": https://raw.githubusercontent.com/steeltoeoss-incubator/steeltoe-schema/master/schema.json
Logging:
  IncludeScopes: false
  LogLevel:
    Articulate: Trace
Eureka:
  Instance:
    IsNonSecurePortEnabled: false
    SecurePortEnabled: true
#    SecurePort: 65419
    InstanceId: "${random:uuid}"
    HomePageUrlPath: "/"
    StatusPageUrlPath: "/"
    HealthCheckUrlPath: "/actuator/health"
    HostName: localhost
    RegistrationMethod: local

