---
"$schema": https://raw.githubusercontent.com/steeltoeoss-incubator/steeltoe-schema/master/schema.json
vcap:
  application:
    application_id: 14b3a6e1-d5ed-4b9a-9324-d501e3794e80
    application_name: ers
    application_version: 7654331f-0905-4d62-b709-5792086bd5f1
    cf_api: https://api.sys.coalinga.cf-app.com
    limits:
      disk: 1024
      fds: 16384
      mem: 768
    name: ers
    organization_id: 83904768-64fa-4304-9b06-4f08e2f6fe79
    organization_name: rcaf
    process_id: 14b3a6e1-d5ed-4b9a-9324-d501e3794e80
    process_type: web
    space_id: 29a686c9-5a54-44d2-865d-99a10c2aa646
    space_name: presenter
    users:
    version: 7654331f-0905-4d62-b709-5792086bd5f1
