version: '3.0'
services:
  sync:
    image: ${APP_NAME}:live-sync
    volumes:
      - ~/.cf:/root/.cf
      - ${APP_DIR}:/app
      - ${APP_DIR}/bin/.buildsync:/syncorig # work around sync folder being available during first build inside /syncorig and then updated by tilt during livesync into /sync
    environment:
      APP_NAME: ${APP_NAME}
      AssemblyName: ${AssemblyName}
      CF_PUSH_INIT: ${CF_PUSH_INIT}
