version: "3.0"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    volumes:
      # - ./data/sqlserver:/var/opt/mssql
      - sqlServerData:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssword

  configserver:
    image: steeltoeoss/config-server
    restart: always
    ports:
      - "8888:8888"
    volumes: 
      - ./config:/config
    environment:
      #SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/tanzu-solutions-engineering/funny-quotes-config
      #SPRING_PROFILES_ACTIVE: git
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: /config
      SPRING_PROFILES_ACTIVE: native
    #env_file: config-server.env

  eureka:
    image: steeltoeoss/eurekaserver
    ports:
      - "8761:8761"
    platform: linux
    environment:
      eureka_server_enableSelfPreservation: "false"

  spring-boot-admin:
    image: steeltoeoss/spring-boot-admin
    ports: 
      - "9090:8080"

  mysql:
     image: mysql:5.7
     volumes:
       - mySqlData:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - mysql
    environment:
     - PMA_HOST=mysql
     - PMA_USER=root
     - PMA_PASSWORD=
    restart: always
    ports:
     - 8083:80
    volumes:
     - /sessions
      
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    


volumes:
  mySqlData:
  sqlServerData: