---
"$schema": https://raw.githubusercontent.com/steeltoeoss-incubator/steeltoe-schema/master/schema.json
Eureka:
  Instance:
    RegistrationMethod: direct
    SecurePort: 8443
    SecurePortEnabled: true
    SecureVipAddress: localhost.internal